### ISSUE TITLE
The npm package is missing files, all folders are empty

### ISSUE THREAD

**Issue by Vlad-Zhukov** [joshburgess/redux-most#1]

**Comment by joshburgess** [comment]
Something is wrong in the 0.2.0 build... I think it's related to upgrading to Webpack 2. Thanks for letting me know. I will try to fix it today. You should be able to use the the 0.1.8 version in the meantime.

**Comment by joshburgess** [comment]
This has been fixed. There is some kind of problem with using yarn to publish packages that I don't yet understand. I republished via npm, and it seems to be fixed now. Please, use the latest version of the package (0.2.2). I will try to look into the yarn problem. Thanks again for bringing this to my attention.

**Comment by joshburgess** [comment]
@Vlad-Zhukov This was the reason why... https://github.com/yarnpkg/yarn/issues/2942
