### ISSUE TITLE
Setup gitter community

### ISSUE THREAD

**Issue by jshthornton** [joshburgess/redux-most#12]
It would be good to have a few gitter channels for things such as support, general discussion, and what not.

**Comment by joshburgess** [comment]
I was thinking about doing this, but wasn't sure if there were enough users to bother. haha. but yeah, it's probably a good idea now that a few people are starting to contribute. I'll try to create one tonight.

**Comment by joshburgess** [comment]
I actually just went ahead and made it just now.

https://gitter.im/redux-most

We should add a link to it in the README soon.

**Comment by joshburgess** [comment]
@jshthornton looks like it forked the repo to add a badge or something, but I don't see the bade in their fork. do you know how that works?

**Comment by jshthornton** [comment]
You should just be able to use this
https://img.shields.io/gitter/room/nwjs/nw.js.svg

Then add a link to it.
