### ISSUE TITLE
Updating to @most/core

### ISSUE THREAD

**Issue by kanitsharma** [joshburgess/redux-most#31]
Big fan of this library, thanks for all the efforts.
@most/core provides curried functions and a tree-shakeable package, should we consider updating?
Plus updating from @most/core to most 2.0 will be non-breaking.

I will be happy to send a PR :).

**Comment by joshburgess** [comment]
@kanitsharma Yes, I am interested in upgrading. Sorry, I've been really busy recently. I don't have a whole lot of time at the moment, but I am open to PRs.

The important part will be getting the use of subjects correct. I'm not sure whether or not the current @most/core-compatible solution for subjects still has both async and sync modes, but we MUST use sync mode for timing to function as it does now.

Originally, I used the async mode and someone discovered timing problems (this can be found in the closed issues). So, I switched to sync.

I would also appreciate improvements to the unit tests if you're up for it. :)

**Comment by joshburgess** [comment]
Also, are you sure this is non-breaking? Can you explain?

I believe we should probably jump to a new major version when doing this.

**Comment by kanitsharma** [comment]
@joshburgess The most-subject version we are using is pretty old and the latest version which has support for @most/core has breaking changes in the API. I'd suggest you have a look once.
https://github.com/mostjs-community/subject
However i think we can use @most/create for imperatively pushing actions and epics and it provides a pretty straightforward API to do so, correct me I am wrong :)

**Comment by kanitsharma** [comment]
> Also, are you sure this is non-breaking? Can you explain?
>
From the most.js repo

![image](https://user-images.githubusercontent.com/23506120/45986559-e764de00-c089-11e8-8347-dafbba500ae6.png)

**Comment by kanitsharma** [comment]
> I would also appreciate improvements to the unit tests if you're up for it. :)
Sure :+1:

**Comment by kanitsharma** [comment]
hey @joshburgess, i guess I was wrong about @most/create it still has a dependency of Most 1.0.
But @most/core already comes with Multicast so I am using that, will land a PR soon :+1:

**Comment by kanitsharma** [comment]
Closing this as the PR #32 is merged.
