### ISSUE TITLE
Add and start using a Continuous Integration tool

### ISSUE THREAD

**Issue by joshburgess** [joshburgess/redux-most#7]
# Add and start using a Continuous Integration tool

_Requirement: must be a free option for open source_

### Potential options:

- CodeShip
- Jenkins
- CircleCI (Does this provide any free version for open source projects yet?)
- Travis
- Any others?

**Comment by jshthornton** [comment]
I'm a big fan of Travis for open source. It supports docker so you can setup cleaner environments for tests

**Comment by joshburgess** [comment]
Thanks. Added it to the list.

**Comment by jshthornton** [comment]
@joshburgess If we do decide to go with Travis I'd happily take on the work.

**Comment by joshburgess** [comment]
@jshthornton Are any of the other options completely free for open source? I've used CodeShip before and liked it, but I believe it has a limit on the number of pushes allowed each month for free accounts. Have also used CircleCI before at work, but not 100% clear about what they offer for open source.

**Comment by joshburgess** [comment]
@jshthornton I'll get back to you about this soon. I want to look into CodeShip and Circle CI a little more to see exactly what their restrictions are for open source.
