### ISSUE TITLE
Consider switching from Webpack to Rollup

### ISSUE THREAD

**Issue by joshburgess** [joshburgess/redux-most#9]
# Consider Switching from Webpack to Rollup

I attempted this once in the past and ended up with a larger build size than I was getting with Webpack at the time and just gave up on it, but I may have been doing something wrong. 

I'd like to try it again soon and see if I can get things working properly.

**Comment by Vlad-Zhukov** [comment]
Rollup doesn't support Babel 7.

**Comment by joshburgess** [comment]
@Vlad-Zhukov Hmmm. Interesting.

That reminds me. I need to update the Babel & ESLint settings being used in the project.

**Comment by joshburgess** [comment]
@Vlad-Zhukov do you have any links for me to look at about the Rollup & Babel 7 problem?

**Comment by Vlad-Zhukov** [comment]
@joshburgess nope, I couldn't find anything. When you try to run it, it simply throws with a error like `cannot get property 'value' of undefined` as far as I remember.

**Comment by joshburgess** [comment]
Closing this for now as I wasn't able to get a smaller build with Rollup.
